### ISSUE TITLE
Feature Request: Font Sizing.

### ISSUE THREAD

**Issue by MikeGuest** [wassy92x/lovelace-digital-clock#11]
Hi.

I love this add-on - my only issue is, i'm using it as the last button on my menu line, and the size of the fonts causes the tile to be truncated on  my tablets. (example below)

I'd love an easy way to specify the date and time font sizes (separately if possible) in the yaml.

![image](https://user-images.githubusercontent.com/12844043/144432550-660db576-8a6f-4a5f-93c2-50d3cc75dd80.png)

Thanks

**Comment by wassy92x** [comment]
If you like to change the font size please use card-mod.
https://github.com/thomasloven/lovelace-card-mod

If you need some help, you can respond to this issue.

**Comment by MikeGuest** [comment]
is it possible to use card-mod to change the text size of each line independently?

Thanks

**Comment by LUBANG37** [comment]
My configuration:

GRID

- first:

type: custom:digital-clock
dateFormat: ' '
card_mod:
  style: |
    .type-custom-digital-clock {
      font-size: 40px !important; 
      font-weight: bold !important;
      color: orange;
    }

- next...

type: custom:digital-clock
timeFormat: ' '
dateFormat:
  weekday: long
  day: 2-digit
  month: short
card_mod:
  style: |
    .type-custom-digital-clock {
      font-size: 15px !important; 
      font-weight: normal !important;
      color: orange;
    }
![window](https://user-images.githubusercontent.com/26896616/150790551-d7319ca9-fa92-46c7-9209-8bd4a17ea7ab.JPG)

**Comment by smartroad** [comment]
Just in case anyone else finds this like I did to figure out how to change font size, you can change the each line without having to have two cards:

```
type: custom:digital-clock
dateFormat:
  weekday: long
  day: 2-digit
  month: short
  year: numeric
timeFormat:
  hour: 2-digit
  minute: 2-digit
  second: 2-digit
card_mod:
  style: |
    .first-line {
      font-size: 56px !important;}
    .second-line {
      font-size: 8px !important;}
```

![image](https://user-images.githubusercontent.com/1229033/176997759-963ca64c-620f-47e0-bcc3-deb7fe0e783b.png)

**Comment by MikeGuest** [comment]
> card_mod:
>   style: |
>     .first-line {
>       font-size: 56px !important;}
>     .second-line {
>       font-size: 8px !important;}

Works for me. Many thanks
