### ISSUE TITLE
Any way to make card fully transparent?

### ISSUE THREAD

**Issue by astirling01** [wassy92x/lovelace-digital-clock#18]
Love the clock and its clean look. Is there any way to make the card fully transparent so that time essentially sits on the background without any surround?

**Comment by markfrancisonly** [comment]
Try the following with card_mod

type: custom:digital-clock
timeFormat:
  hour: numeric
  minute: 2-digit
card_mod:
  style: |
    ha-card {
      --ha-card-background: transparent;
      box-shadow: none;
      font-size: larger;
      font-weight: var(--paper-font-headline_-_font-weight)  !important;
    }
