### ISSUE TITLE
enable 24 hour time

### ISSUE THREAD

**Issue by DERFAUSt** [wassy92x/lovelace-digital-clock#22]
hello :).....  

how do i enable 24 hour time?....

also....how do you use 'firstLineFormat'?.....what is the format?.....been messing with it...could you post a more complicated example?...  i appreciate your time and effort :)

thank you :)

**Comment by mtfurlan** [comment]
time/dateFormat can be strings, and they accept [moment formatting stuff](https://moment.github.io/luxon/#/formatting?id=table-of-tokens)
```
type: custom:digital-clock
timeFormat: HH:mm:ss
dateFormat: yyyy-MM-dd LLL ccc
```

I also found it confusing till I read the words carefully, I think changing the example would help a lot:
```diff
diff --git a/README.md b/README.md
index b4de0ab..50a3e48 100644
--- a/README.md
+++ b/README.md
@@ -33,9 +33,7 @@ dateFormat:
   weekday: 'long'
   day: '2-digit'
   month: 'short'
-timeFormat:
-  hour: '2-digit'
-  minute: '2-digit'
+timeFormat: HH:mm:ss
```
