### ISSUE TITLE
Deprecation of polymer

### ISSUE THREAD

**Issue by robinostlund** [wassy92x/lovelace-digital-clock#29]
Hi,
Noticed today when i upgraded HA to 2023.4.0 that polymer is not going to be supported in 2023.5.0.
https://developers.home-assistant.io/blog/2023/04/04/deprecating_polymer/

And i saw that this repository uses that one. Any plans on replacing polymer with LIT? 😄 

Brg
Robin

**Comment by wassy92x** [comment]
It uses already Lit. Where did you see, that it uses Polymer?

**Comment by robinostlund** [comment]
It exists in the latest release it seems and i get an warning from HA for it 😄 
https://github.com/wassy92x/lovelace-digital-clock/releases/download/v1.2.2/digital-clock.js
``
`grep polymer digital-clock.js | wc -l
65```

**Comment by wassy92x** [comment]
It seems like it was included in a dependency. I released a new version

**Comment by robinostlund** [comment]
Lovely thanks :)
