### ISSUE TITLE
Add Text behind Clock

### ISSUE THREAD

**Issue by PenthouseLA** [wassy92x/lovelace-digital-clock#31]
is it possible to add a text behind the Clock?

**Comment by wassy92x** [comment]
What do you mean exactly with that?

**Comment by PenthouseLA** [comment]
![image](https://github.com/wassy92x/lovelace-digital-clock/assets/129676397/4ec48121-3a58-4372-b5e0-d803b243b64a)
 Text behind the clock time (Text in Red :))

**Comment by shbatm** [comment]
If you just want static text, you can do this by [escaping the string](https://moment.github.io/luxon/#/formatting?id=escaping) in the config.

For example, above would be:

```yaml
firstLineFormat: "T 'Clock'"
```
