### ISSUE TITLE
24h TIME

### ISSUE THREAD

**Issue by Monacoslo** [wassy92x/lovelace-digital-clock#34]
We are using 24h time format. How to make it show 24h time and get rid of AM/PM symbols?

**Comment by gabimal** [comment]
I subscrie to this, we need 24h time format

**Comment by wassy92x** [comment]
It's already possible by either setting your correct locale in your home assistant profile or by setting the property 'locale' correctly.

**Comment by gabimal** [comment]
Hi Fabian,

Thanks a lot for your quick answer!
Unless I'm doing something wrong or there's something I do not undestand, my setup looks like this:

[cid:25506b1d-1e7a-47ee-ba91-0df068dcadc7]    this is the clock card

[cid:b9ee33fc-4528-4b89-8a58-b9f3243bb843]  and this is my profile setup.

As you can see the time is set in 24H format. Any idea what could be wrong?

Thanks in advance!


Best regards,
Gabriel


________________________________

**Comment by wassy92x** [comment]
Unfortuntaly I can't see the pictures.

**Comment by gabimal** [comment]
I can use a file transfer service to send you the pictures. Is this address ok?
***@***.***

Thank you!

________________________________
