### ISSUE TITLE
24 Hour

### ISSUE THREAD

**Issue by jjanderson** [wassy92x/lovelace-digital-clock#35]
Hello,

Is there a way to stipulate 24 hour clock format?

i.e 14:30 as opposed to 02:30?

Many thanks

**Comment by yatush** [comment]
You can add:

cards:
    - type: custom:digital-clock
      **firstLineFormat: 'H:MM'**

For this.

**Comment by yatush** [comment]
This worked for me:

**Comment by IoT-CI-Ltd** [comment]
Found the issue, and all sorted now, thanks for your help

**Comment by FelixPopp** [comment]
`firstLineFormat: HH:MM` did not work for me. It showed the month instead of minutes.
With `firstLineFormat: HH:mm` it works correct for me.

https://moment.github.io/luxon/#/formatting?id=toformat
