### ISSUE TITLE
24 hour time?

### ISSUE THREAD

**Issue by chuck99z28** [wassy92x/lovelace-digital-clock#38]
Is there a setting for 24 hour clock.  1600 vice 04:00 PM

**Comment by wassy92x** [comment]
Yes.
Firstly the displayed format is dependent on the locale. For example we in Germany (locale de) always dispay the time in 24hours format and for example in England (locale en) the default for a time is the 12h format. To set the locale either set the locale property in the card or set the correct locale in your home assistant profile. Another possibility is to set the format explicitly. In your case the property timeFormat has to be set to HH:mm
