### ISSUE TITLE
12hr Display Mode

### ISSUE THREAD

**Issue by NexGen-3D-Printing** [wassy92x/lovelace-digital-clock#39]
First up, a quick thanks, this clock is 99% perfect, just the 12/24hr thing was bugging me and I seen nothing in the documentation on changing it, so I decided to mess about and figured it out.

Just in case anyone else is wondering, as every single clock I looked at for Home Assistant was using 24hr mode, the following will give you 12hr mode as wifes and kids dont understand 24hr clocks properly:

type: custom:digital-clock
timeFormat: h:mm a
dateFormat:
  weekday: long
  day: 2-digit
  month: short

This will display your clock like this:

![Clock](https://github.com/wassy92x/lovelace-digital-clock/assets/20825418/63213109-23ea-4069-bf2f-083cadf06cd8)

**Comment by kvoth1** [comment]
How do I set to 24 hour? It’s defaulting to 12 hour when using the sample code for me when I always use 24 hour. :)

Edit:  figured it out
timeformat: HH:mm

**Comment by wassy92x** [comment]
Firstly the displayed format is dependent on the locale. For example we in Germany (locale de) always dispay the time in 24hours format and for example in England (locale en) the default for a time is the 12h format. To set the locale either set the locale property in the card or set the correct locale in your home assistant profile. Another possibility is to set the format explicitly. In your case the property timeFormat has to be set to HH:mm
