### ISSUE TITLE
Weekday Truncating

### ISSUE THREAD

**Issue by wgumaa** [wassy92x/lovelace-digital-clock#41]
First, let me start by saying thatI love this card! Easy to use and set up and looks good! 

I recently ran into an issue when tried to use the card in a grid. I have a grid comprising of 2 columns. The left column is 95% and contains the clock card and right column is 5% and has a chip card. 

![image](https://github.com/wassy92x/lovelace-digital-clock/assets/105917603/26667724-7c68-4909-8220-325db5ffa171)

Despite the fact that I set the weekday: 'long' it displays the short one and I cannot figure out why? 

Here is the code for my card:

`type: custom:layout-card
layout_type: custom:grid-layout
layout_options:
  grid-template-columns: 95% 5%
  grid-template-rows: auto
  grid-template-areas: |
    "left right"
cards:
  - type: custom:digital-clock
    dateFormat: null
    weekday: long
    day: 2-digit
    month: long
    timeFormat: HH:mm
    hour: 2-digit
    minute: 2-digit
    seconds: 2-digit
    card_mod:
      style:
        .: |
          ha-card {
            background-color: transparent;
            box-shadow: none;
            border: 0px; 
          }
    view_layout:
      grid-area: left
  - type: custom:mushroom-chips-card
    chips:
      - type: template
        entity: alarm_control_panel.evo192_partition_area_1
        tap_action:
          action: none
        hold_action:
          action: none
        double_tap_action:
          action: none
        icon: |-
          {% set state = states(entity) %}
          {% if state == 'armed' %}
          mdi:shield-lock
          {% elif state == 'disarmed' %}
          mdi:shield-lock-open
          {% endif %}
        icon_color: |-
          {% set state = states(entity) %}
          {% if state == 'armed' %}
          red
          {% else %}
          green
          {% endif %}
    alignment: center
    card_mod:
      style: |
        ha-card {
          --chip-icon-size: 30px;
          --chip-height: 75px;
          
          --chip-border-width: 0px;
          --chip-box-shadow: none;
          --chip-background: none; 
        }
    view_layout:
      grid-area: right`

Is it my coding so something with the card?

**Comment by wassy92x** [comment]
Unfortunately  I can't confirm, that your indentation is correct. Please edit your comment and make sure that your config is correctly formatted by using three \` in the beginning and three \` after your code block.

**Comment by wgumaa** [comment]
Have done so now.

**Comment by wgumaa** [comment]
Figured it out. It was indentation starinting with weekday anf the removal of null from dateFormat.
