### ISSUE TITLE
24 hour clock?

### ISSUE THREAD

**Issue by andywarburton** [wassy92x/lovelace-digital-clock#42]
Hi, thanks for this addon, it's super useful - is it possible to set the time to use a 24 hour clock instead of AM/PM ?

Thanks!

**Comment by wassy92x** [comment]
As already metioned in #39, firstly the displayed format is dependent on the locale. For example we in Germany (locale de) always dispay the time in 24hours format and for example in England (locale en) the default for a time is the 12h format. To set the locale either set the locale property in the card or set the correct locale in your home assistant profile. Another possibility is to set the format explicitly. In your case the property timeFormat has to be set to HH:mm
