### ISSUE TITLE
Missing colon in Clock display for locale DA

### ISSUE THREAD

**Issue by Devoman71** [wassy92x/lovelace-digital-clock#49]
Clock does not have a colon ":" between Hour and Minutes for Locale DA. It´s there if I change Locale to DE.

**Comment by wassy92x** [comment]
Hm this is very weird.
The shown format is dependent on the browser implemention.
One walkaround would be to set the firstLineFormat to "HH:mm"

**Comment by Devoman71** [comment]
Hi
yes it's weird when the browser is using DA
I will try the suggested solution by setting the firstLineFormat tp "HH:mm"
Thanks for quick response


________________________________
Fra: Fabian ***@***.***>
Sendt: 14. november 2024 23:33
Til: wassy92x/lovelace-digital-clock ***@***.***>
Cc: Devoman71 ***@***.***>; Author ***@***.***>
Emne: Re: [wassy92x/lovelace-digital-clock] Missing colon in Clock display for locale DA (Issue #49)


Hm this is very weird.
The shown format is dependent on the browser implemention.
One walkaround would be to set the firstLineFomat to "HH:mm"

**Comment by Devoman71** [comment]
Thanks it works with this "code"

type: custom:digital-clock
locale: da
firstLineFormat: "HH:MM"
secondLineFormat: "dd. MMMM yyyy"

You may close this topic with a work-around solution.
