### ISSUE TITLE
24 hour

### ISSUE THREAD

**Issue by fotis3d** [wassy92x/lovelace-digital-clock#5]
Hi there.
Is there a way to get a 24h time format instead of am/pm ?

Thanks

**Comment by wassy92x** [comment]
Yes this is possible. Either by setting `locale` to a country-code which uses typacally the 24h time format e.g. 'de' or by setting timeFomat to a string respectively the desired format: `HH:mm:ss`

**Comment by fotis3d** [comment]
yeap worked. 
thanks
;)
