### ISSUE TITLE
Feature request: Background picture

### ISSUE THREAD

**Issue by Korte68** [wassy92x/lovelace-digital-clock#6]
Thank you for your work:) May I suggest something?
1. It would be great if we can set a background picture for the card. It would be even better If it can change automatically based on time (night mode/day mode )
2. Display  a custom text (for example name day).
Thank you

**Comment by pickonedev** [comment]
You can do this with Card-Mod.

`    card_mod:
      style: |
        :host {
        color:
        {% set calc = states('variable.bedroom_balcony_temphum_battery') %}
        {% if calc <= "10" %}
        red
        {% else %}
        lime
        {% endif %}`

I made a battery sensor which changes the color by the value of the state... You can do this with the value from the time, by adding different backgrounds to the card. Even more nicer, you can make the font bleding as exclusion, then you can see the text no matter what colors you have in the background...

**Comment by wassy92x** [comment]
I will not implent this, because it is already possible by using card mod (see upper answer)
